In [1]:
import pandas as pd

Import Budget Information for the 32 districts in NYC

In [2]:
nycdistricts = pd.read_csv('../Datasets/NYCSchoolDistricts.csv')
nycdistricts.columns

Index(['District', 'School Code', 'School Name', 'School Type',
       'Weighted Register Allocation',
       'Weighted Register Allocation If FSF Fully Funded',
       'Weighted Register Allocation Gap to 100%', '% Funded',
       'Foundation \r\n(not included in the funding %)',
       'Collective Bargaining for School Based Staff (not included in the funding %)',
       'Total FSF Allocation Including Foundation and Collective Bargaining Costs',
       'Total FSF Allocation at 100% Including Foundation & Adjusted for Collective Bargaining Costs',
       'Total FSF Allocation Gap to 100% Including Foundation & Adjusted for Collective Bargaining Costs',
       'Total Budget Allocation', 'FSF as % of Total Budget Allocation',
       'Non-FSF Budget Allocations'],
      dtype='object')

In [3]:
#Isolate two columns needed
nycdistrictsinfo = nycdistricts[['District','Total Budget Allocation']]
nycdistrictsinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   District                 1608 non-null   object
 1   Total Budget Allocation  1608 non-null   object
dtypes: object(2)
memory usage: 25.2+ KB

In [4]:
nycdistrictsinfo.head()

  District Total Budget Allocation
0       01           $   4,966,456
1       01           $   7,977,207
2       01           $   9,114,056
3       01           $   7,329,616
4       01           $   5,840,771

In [5]:
#Add needed information to empty list

totalbudget = []

for i in nycdistrictsinfo['Total Budget Allocation']:
    totalbudget.append(i)

In [6]:
#Clean up data

totalbudget = [x.replace('$', '') for x in totalbudget]
totalbudget = [x.replace(' ', '') for x in totalbudget]
totalbudget = [x.replace(',', '') for x in totalbudget]

nycdistrictsinfo['Total Budget Allocation'] = totalbudget
nycdistrictsinfo.head()

C:\Users\Yiqing Guo\AppData\Local\Temp\ipykernel_4772\308010859.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nycdistrictsinfo['Total Budget Allocation'] = totalbudget

  District Total Budget Allocation
0       01                 4966456
1       01                 7977207
2       01                 9114056
3       01                 7329616
4       01                 5840771

In [7]:
#Change column to numeric

nycdistrictsinfo['Total Budget Allocation'] = pd.to_numeric(nycdistrictsinfo['Total Budget Allocation'])

C:\Users\Yiqing Guo\AppData\Local\Temp\ipykernel_4772\1943056143.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nycdistrictsinfo['Total Budget Allocation'] = pd.to_numeric(nycdistrictsinfo['Total Budget Allocation'])

In [8]:
#Group by district to get total funding per district

districtbudget = nycdistrictsinfo.groupby('District').sum()
districtbudgetlist = []
for i in districtbudget['Total Budget Allocation']:
    districtbudgetlist.append(i)
print(districtbudgetlist)

[200591725, 946172546, 352123037, 246147021, 216954795, 391676770, 360439960, 493947174, 616340058, 914314503, 627403714, 391938125, 324995162, 319761813, 539612949, 135184883, 366965145, 253044431, 391242220, 783381385, 575292720, 535629979, 178523951, 887265884, 570229915, 437105316, 717548919, 576686058, 400675834, 591321152, 1096239269, 206636804, 154477899, 1936630130, 17736501242]

In [9]:
#Read in districtinfo csv

districtinfo = pd.read_csv('../Datasets/PreliminaryDistrictDataWITHMEDIANINCOME2.csv')
districtinfo.head()

,Unnamed: 0.1,Unnamed: 0,DistrictName,GraduationPercentageRate,DropoutPercentageRate,FundingPerStudent,TotalEnrolled,MalesEnrolled,FemalesEnrolled,Percentage of Minority Students,HouseholdIncome
0,0,0,ADDISON CSD,90,3,23833.02,976,503,473,3.2,59328.0
1,1,1,ADIRONDACK CSD,92,5,14013.61,1145,575,570,1.7,63986.4
2,2,2,AFTON CSD,83,10,24128.02,507,262,245,8.9,54818.3
3,3,3,AKRON CSD,95,3,17552.56,1334,667,667,17.5,76903.8
4,4,4,ALBANY CITY SCHOOL DISTRICT,71,12,22382.65,8610,4444,4166,80.2,61049.2

In [10]:
#Find what index the NYC Districts are located 

districtinfo[districtinfo['DistrictName'].str.contains('NYC')]

,Unnamed: 0.1,Unnamed: 0,DistrictName,GraduationPercentageRate,DropoutPercentageRate,FundingPerStudent,TotalEnrolled,MalesEnrolled,FemalesEnrolled,Percentage of Minority Students,HouseholdIncome
441,441,448,NYC GEOG DIST # 1 - MANHATTAN,68,8,NaN,10473,5481,4992,81.6,77936.0
442,442,449,NYC GEOG DIST # 2 - MANHATTAN,81,5,NaN,59568,28456,31112,73.4,127276.0
443,443,450,NYC GEOG DIST # 3 - MANHATTAN,81,3,NaN,21132,9599,11533,66.5,104303.7
444,444,451,NYC GEOG DIST # 4 - MANHATTAN,85,4,NaN,11510,5594,5916,95.0,31104.5
445,445,452,NYC GEOG DIST # 5 - MANHATTAN,74,5,NaN,9332,4954,4378,93.6,50067.0
446,446,453,NYC GEOG DIST # 6 - MANHATTAN,75,5,NaN,19124,9709,9415,94.4,55738.5
447,447,454,NYC GEOG DIST # 7 - BRONX,69,9,NaN,16318,8639,7679,98.5,36670.8
448,448,455,NYC GEOG DIST # 8 - BRONX,66,13,NaN,24613,12660,11953,94.4,44250.0
449,449,456,NYC GEOG DIST # 9 - BRONX,74,9,NaN,29653,14989,14664,98.7,32099.8
450,450,457,NYC GEOG DIST #10 - BRONX,80,7,NaN,49381,25187,24194,94.1,47554.0
451,451,458,NYC GEOG DIST #11 - BRONX,75,8,NaN,35438,18643,16795,91.1,59079.6
452,452,459,NYC GEOG DIST #12 - BRONX,63,12,NaN,19427,10007,9420,98.6,36342.3
453,453,460,NYC GEOG DIST #13 - BROOKLYN,90,2,NaN,19994,10672,9322,82.8,100631.6
454,454,461,NYC GEOG DIST #14 - BROOKLYN,82,5,NaN,16583,8684,7899,85.1,70139.6
455,455,462,NYC GEOG DIST #15 - BROOKLYN,71,5,NaN,29846,14881,14965,69.9,95562.1
456,456,463,NYC GEOG DIST #16 - BROOKLYN,60,5,NaN,5425,2891,2534,97.3,54048.0
457,457,464,NYC GEOG DIST #17 - BROOKLYN,74,6,NaN,19019,9361,9658,96.9,62593.0
458,458,465,NYC GEOG DIST #18 - BROOKLYN,67,6,NaN,12417,6499,5918,96.6,53702.3
459,459,466,NYC GEOG DIST #19 - BROOKLYN,79,6,NaN,19389,10230,9159,97.9,39264.3
460,460,467,NYC GEOG DIST #20 - BROOKLYN,76,7,NaN,49535,25915,23620,75.5,63385.7
461,461,468,NYC GEOG DIST #21 - BROOKLYN,77,6,NaN,33868,17379,16489,67.6,53230.8
462,462,469,NYC GEOG DIST #22 - BROOKLYN,85,3,NaN,31931,16127,15804,67.4,67778.1
463,463,470,NYC GEOG DIST #23 - BROOKLYN,52,12,NaN,7714,4315,3399,98.7,38831.5
464,464,471,NYC GEOG DIST #24 - QUEENS,80,5,NaN,54124,28429,25695,86.8,73961.0
465,465,472,NYC GEOG DIST #25 - QUEENS,76,5,NaN,35583,18163,17420,88.7,67681.3
466,466,473,NYC GEOG DIST #26 - QUEENS,92,3,NaN,30802,15826,14976,84.7,89223.3
467,467,474,NYC GEOG DIST #27 - QUEENS,76,10,NaN,40675,21347,19328,90.0,74852.8
468,468,475,NYC GEOG DIST #28 - QUEENS,84,5,NaN,38378,19482,18896,84.4,72971.7
469,469,476,NYC GEOG DIST #29 - QUEENS,77,6,NaN,23776,12395,11381,98.2,80180.1
470,470,477,NYC GEOG DIST #30 - QUEENS,86,4,NaN,36697,18539,18158,83.4,72604.3
471,471,478,NYC GEOG DIST #31 - STATEN ISLAND,84,4,NaN,57787,29605,28182,55.6,86134.6
472,472,479,NYC GEOG DIST #32 - BROOKLYN,75,8,NaN,9850,5045,4805,97.6,52066.0
473,473,481,NYC SPEC SCHOOLS - DIST 75,—,—,NaN,25358,18632,6726,87.3,NaN

In [11]:
#Get the enrollment values in a list

NYCTotalEnrolled = []
for i in districtinfo['TotalEnrolled'].loc[441:473]:
    NYCTotalEnrolled.append(i)
print(NYCTotalEnrolled)

[10473, 59568, 21132, 11510, 9332, 19124, 16318, 24613, 29653, 49381, 35438, 19427, 19994, 16583, 29846, 5425, 19019, 12417, 19389, 49535, 33868, 31931, 7714, 54124, 35583, 30802, 40675, 38378, 23776, 36697, 57787, 9850, 25358]

In [12]:
#Divide both lists to get funding per student per district

districtfundingperchild = [i / j for i, j in zip(districtbudgetlist, NYCTotalEnrolled)]
districtfundingperchild = [round(num,2) for num in districtfundingperchild]
print(districtfundingperchild)

[19153.22, 15883.91, 16663.02, 21385.49, 23248.48, 20480.9, 22088.49, 20068.55, 20785.08, 18515.51, 17704.26, 20174.92, 16254.63, 19282.51, 18079.91, 24918.87, 19294.66, 20378.87, 20178.57, 15814.7, 16986.32, 16774.61, 23142.85, 16393.21, 16025.35, 14190.81, 17641.03, 15026.48, 16852.11, 16113.61, 18970.34, 20978.36, 6091.88]

In [13]:
#Update column values 

one = 0

for i in range (441,474):

    districtinfo.at[i, 'FundingPerStudent'] = districtfundingperchild[one]

    one = one + 1

In [14]:
#Confirm column was updated
districtinfo[districtinfo['DistrictName'].str.contains('NYC')]

,Unnamed: 0.1,Unnamed: 0,DistrictName,GraduationPercentageRate,DropoutPercentageRate,FundingPerStudent,TotalEnrolled,MalesEnrolled,FemalesEnrolled,Percentage of Minority Students,HouseholdIncome
441,441,448,NYC GEOG DIST # 1 - MANHATTAN,68,8,19153.22,10473,5481,4992,81.6,77936.0
442,442,449,NYC GEOG DIST # 2 - MANHATTAN,81,5,15883.91,59568,28456,31112,73.4,127276.0
443,443,450,NYC GEOG DIST # 3 - MANHATTAN,81,3,16663.02,21132,9599,11533,66.5,104303.7
444,444,451,NYC GEOG DIST # 4 - MANHATTAN,85,4,21385.49,11510,5594,5916,95.0,31104.5
445,445,452,NYC GEOG DIST # 5 - MANHATTAN,74,5,23248.48,9332,4954,4378,93.6,50067.0
446,446,453,NYC GEOG DIST # 6 - MANHATTAN,75,5,20480.90,19124,9709,9415,94.4,55738.5
447,447,454,NYC GEOG DIST # 7 - BRONX,69,9,22088.49,16318,8639,7679,98.5,36670.8
448,448,455,NYC GEOG DIST # 8 - BRONX,66,13,20068.55,24613,12660,11953,94.4,44250.0
449,449,456,NYC GEOG DIST # 9 - BRONX,74,9,20785.08,29653,14989,14664,98.7,32099.8
450,450,457,NYC GEOG DIST #10 - BRONX,80,7,18515.51,49381,25187,24194,94.1,47554.0
451,451,458,NYC GEOG DIST #11 - BRONX,75,8,17704.26,35438,18643,16795,91.1,59079.6
452,452,459,NYC GEOG DIST #12 - BRONX,63,12,20174.92,19427,10007,9420,98.6,36342.3
453,453,460,NYC GEOG DIST #13 - BROOKLYN,90,2,16254.63,19994,10672,9322,82.8,100631.6
454,454,461,NYC GEOG DIST #14 - BROOKLYN,82,5,19282.51,16583,8684,7899,85.1,70139.6
455,455,462,NYC GEOG DIST #15 - BROOKLYN,71,5,18079.91,29846,14881,14965,69.9,95562.1
456,456,463,NYC GEOG DIST #16 - BROOKLYN,60,5,24918.87,5425,2891,2534,97.3,54048.0
457,457,464,NYC GEOG DIST #17 - BROOKLYN,74,6,19294.66,19019,9361,9658,96.9,62593.0
458,458,465,NYC GEOG DIST #18 - BROOKLYN,67,6,20378.87,12417,6499,5918,96.6,53702.3
459,459,466,NYC GEOG DIST #19 - BROOKLYN,79,6,20178.57,19389,10230,9159,97.9,39264.3
460,460,467,NYC GEOG DIST #20 - BROOKLYN,76,7,15814.70,49535,25915,23620,75.5,63385.7
461,461,468,NYC GEOG DIST #21 - BROOKLYN,77,6,16986.32,33868,17379,16489,67.6,53230.8
462,462,469,NYC GEOG DIST #22 - BROOKLYN,85,3,16774.61,31931,16127,15804,67.4,67778.1
463,463,470,NYC GEOG DIST #23 - BROOKLYN,52,12,23142.85,7714,4315,3399,98.7,38831.5
464,464,471,NYC GEOG DIST #24 - QUEENS,80,5,16393.21,54124,28429,25695,86.8,73961.0
465,465,472,NYC GEOG DIST #25 - QUEENS,76,5,16025.35,35583,18163,17420,88.7,67681.3
466,466,473,NYC GEOG DIST #26 - QUEENS,92,3,14190.81,30802,15826,14976,84.7,89223.3
467,467,474,NYC GEOG DIST #27 - QUEENS,76,10,17641.03,40675,21347,19328,90.0,74852.8
468,468,475,NYC GEOG DIST #28 - QUEENS,84,5,15026.48,38378,19482,18896,84.4,72971.7
469,469,476,NYC GEOG DIST #29 - QUEENS,77,6,16852.11,23776,12395,11381,98.2,80180.1
470,470,477,NYC GEOG DIST #30 - QUEENS,86,4,16113.61,36697,18539,18158,83.4,72604.3
471,471,478,NYC GEOG DIST #31 - STATEN ISLAND,84,4,18970.34,57787,29605,28182,55.6,86134.6
472,472,479,NYC GEOG DIST #32 - BROOKLYN,75,8,20978.36,9850,5045,4805,97.6,52066.0
473,473,481,NYC SPEC SCHOOLS - DIST 75,—,—,6091.88,25358,18632,6726,87.3,NaN

In [15]:
districtinfo.to_csv('../Datasets/PreliminaryDistrictDataNYCDistrictsFunding3.csv')